[mcp_servers.dart-mcp-server]
command = "dart"
args = [ "mcp-server" ]

[mcp_servers.dart-mcp-server.env]

[mcp_servers.dart-mcp-server.tools.add_roots]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.analyze_files]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.connect_dart_tooling_daemon]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.create_project]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.dart_format]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.dart_fix]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.flutter_driver]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.get_active_location]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.get_app_logs]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.get_runtime_errors]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.get_selected_widget]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.get_widget_tree]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.hot_reload]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.hot_restart]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.hover]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.launch_app]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.list_devices]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.list_running_apps]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.pub]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.pub_dev_search]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.remove_roots]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.resolve_workspace_symbol]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.run_tests]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.set_widget_selection_mode]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.signature_help]
approval_mode = "approve"

[mcp_servers.dart-mcp-server.tools.stop_app]
approval_mode = "approve"
