import 'dart:io';

const _configPath = '.codex/config.toml';
const _serverHeader = '''
[mcp_servers.dart-mcp-server]
command = "dart"
args = [ "mcp-server" ]

[mcp_servers.dart-mcp-server.env]
''';

const _managedBlockStart = '# BEGIN codex-dart-mcp approvals.';
const _managedBlockEnd = '# END codex-dart-mcp approvals.';
const _tools = <String>[
  'add_roots',
  'analyze_files',
  'connect_dart_tooling_daemon',
  'create_project',
  'dart_fix',
  'dart_format',
  'flutter_driver',
  'get_active_location',
  'get_app_logs',
  'get_runtime_errors',
  'get_selected_widget',
  'get_widget_tree',
  'hot_reload',
  'hot_restart',
  'hover',
  'launch_app',
  'list_devices',
  'list_running_apps',
  'pub',
  'pub_dev_search',
  'read_package_uris',
  'remove_roots',
  'resolve_workspace_symbol',
  'run_tests',
  'set_widget_selection_mode',
  'signature_help',
  'stop_app',
];

void main() {
  final file = File(_configPath);
  file.parent.createSync(recursive: true);

  var content = file.existsSync() ? file.readAsStringSync() : '';
  if (!content.contains('[mcp_servers.dart-mcp-server]')) {
    content = content.trimRight();
    content = content.isEmpty ? _serverHeader : '$content\n\n$_serverHeader';
  }

  content = content
      .replaceAll(
        RegExp(
          '${RegExp.escape(_managedBlockStart)}[\\s\\S]*?'
          '${RegExp.escape(_managedBlockEnd)}\\n?',
          multiLine: true,
        ),
        '',
      )
      .trimRight();

  final buffer = StringBuffer()
    ..writeln()
    ..writeln()
    ..writeln(
      '$_managedBlockStart Regenerated by '
      '`dart tool/sync_codex_dart_mcp_approvals.dart`.',
    );

  for (final tool in _tools) {
    buffer
      ..writeln('[mcp_servers.dart-mcp-server.tools.$tool]')
      ..writeln('approval_mode = "approve"')
      ..writeln();
  }

  buffer.write(_managedBlockEnd);

  file.writeAsStringSync('$content${buffer.toString()}\n');
}
